name: Run Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: test
      run: make test
    
    - name: diff
      run: |
        ./lexer.exe < recursive-dissent_A2.nc > test.out
        diff ./test.out ./expected.out
